version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    env_file:
      - ./dash_app/.env
    environment:
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - APP_TITLE=${APP_TITLE}
    ports:
      - "8050:8050"
    command: gunicorn -w 3 -b :8050 app:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - dash_app
