version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/
    ports:
      - 8050:80
    networks:
      - my-network
    depends_on:
      - dash
  dash:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dash
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app:server"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - dash-app

networks:
  my-network:
